name: Test Dockerfiles

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4, 8.0, 8.1 ]
    steps:
      - uses: actions/checkout@v3

      - name: Build with PHP {{ matrix.php-version }}
        run: docker build --progress=plain --file {{ matrix.php-version }}/Dockerfile .
