name: Test Dockerfiles

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v3
      - name: Build with PHP ${{ matrix.version }}
        run: docker build --progress=plain --file ${{ matrix.version }}/Dockerfile .
